analyzer:
  errors:
    # avoid_function_literals_in_foreach_calls: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    avoid_print: false,
    prefer_single_quotes: true